# Generated by Django 3.1.4 on 2020-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='tecnologias',
            field=models.TextField(blank=True, null=True, verbose_name='Tecnologias'),
        ),
    ]
