# Generated by Django 3.1.7 on 2021-03-18 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_port_tecnologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem certificado')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descricao', models.TextField(verbose_name='Texto')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['published_date'],
            },
        ),
    ]
