# Generated by Django 3.1.7 on 2021-03-25 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_card', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem Card')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem 2')),
                ('titulo_port', models.CharField(max_length=200, verbose_name='Título')),
                ('titulo_ing', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('texto_port', models.TextField(verbose_name='Texto')),
                ('texto_ing', models.TextField(verbose_name='Texto')),
                ('tecnologias', models.TextField(blank=True, null=True, verbose_name='Tecnologias')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link_rep', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Git')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['published_date'],
            },
        ),
    ]
