# Generated by Django 3.1.7 on 2021-03-26 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_portfoliook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem certificado')),
                ('titulo_port', models.CharField(max_length=200, verbose_name='Título português')),
                ('titulo_ing', models.CharField(max_length=200, verbose_name='Título inglês')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descricao_port', models.TextField(verbose_name='Texto português')),
                ('descricao_ing', models.TextField(verbose_name='Texto inglês')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Certificado OK',
                'verbose_name_plural': 'Certificados OK',
                'ordering': ['published_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfoliook',
            options={'ordering': ['published_date'], 'verbose_name': 'Postagem OK', 'verbose_name_plural': 'Postagens OK'},
        ),
        migrations.AlterField(
            model_name='portfoliook',
            name='texto_ing',
            field=models.TextField(verbose_name='Texto inglês'),
        ),
        migrations.AlterField(
            model_name='portfoliook',
            name='texto_port',
            field=models.TextField(verbose_name='Texto português'),
        ),
        migrations.AlterField(
            model_name='portfoliook',
            name='titulo_ing',
            field=models.CharField(max_length=200, verbose_name='Título inglês'),
        ),
        migrations.AlterField(
            model_name='portfoliook',
            name='titulo_port',
            field=models.CharField(max_length=200, verbose_name='Título português'),
        ),
    ]
