# Generated by Django 3.1.7 on 2021-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210325_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='titulo_ing',
            field=models.CharField(max_length=100, verbose_name='Título Inglês'),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='titulo_port',
            field=models.CharField(max_length=100, verbose_name='Título português'),
        ),
    ]
