# Generated by Django 3.1.7 on 2021-03-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210325_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_port', models.CharField(max_length=100, verbose_name='Título português')),
                ('titulo_ing', models.CharField(max_length=100, verbose_name='Título Inglês')),
                ('texto_port', models.TextField()),
                ('texto_ing', models.TextField()),
            ],
        ),
    ]
