# Generated by Django 3.1.7 on 2021-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210325_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_card', models.ImageField(blank=True, null=True, upload_to='port/images', verbose_name='Imagem Card')),
                ('titulo_port', models.CharField(max_length=100, verbose_name='Título português')),
                ('titulo_ing', models.CharField(max_length=100, verbose_name='Título Inglês')),
                ('subtitulo_port', models.CharField(max_length=100, verbose_name='Subtítulo português')),
                ('subtitulo_ing', models.CharField(max_length=100, verbose_name='Subtítulo inglês')),
                ('modal_port', models.TextField(verbose_name='Texto modal português')),
                ('modal_ing', models.TextField(verbose_name='Texto modal inglês')),
            ],
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='subtitulo_ing',
            field=models.CharField(max_length=100, verbose_name='Subtítulo inglês'),
        ),
        migrations.AlterField(
            model_name='formacaocomplementar',
            name='subtitulo_ing',
            field=models.CharField(max_length=100, verbose_name='Subtítulo inglês'),
        ),
        migrations.AlterField(
            model_name='formacaoprofissional',
            name='subtitulo_ing',
            field=models.CharField(max_length=100, verbose_name='Subtítulo inglês'),
        ),
    ]
