# Generated by Django 3.1.7 on 2021-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210325_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardportfolio',
            name='subtitulo_ing',
            field=models.CharField(max_length=300, verbose_name='Subtítulo inglês'),
        ),
        migrations.AlterField(
            model_name='cardportfolio',
            name='subtitulo_port',
            field=models.CharField(max_length=300, verbose_name='Subtítulo português'),
        ),
    ]
